<?php
/**
 * 閲覧側のTOPページ
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Script_Index
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $newPages     ページ一覧ページに表示させるページデータ       
 * @author      suzuki-mar
 */
?>

<?php if (count($this->entries) > 0): ?>

    <?php foreach($this->entries as $id => $entry): ?>
        <!-- entry START --> 
        <div class="entry"><div class="entry"><div class="entry"><div class="entry"><div class="entry"><div class="entry"> 

            <div class="entryHead">
                <h2><span><?php echo $this->escape($entry['title']) ?></span></h2>
                <p><a href="#"><img src="/images/front/setucocms/writer/icn_writer_noimage.png" alt="" /></a></p>
                <dl class="entryInfo">
                    <dt class="date">日付</dt>
                        <dd class="date"><?php echo $this->escape($entry['update_date']) ?></dd>
                    <!-- ><dt class="author">ライター</dt>
                        <dd class="author"><a href="#">author</a></dd> -->
                    <dt class="category">カテゴリー</dt>
                        <dd class="category"><a href="<?php echo $this->baseUrl('page/category/id/' . $this->category['id']) ?>" ><?php echo $this->escape($this->category['name']) ?></a></dd>
                </dl>
                <!-- <dl class="entryComments">
                                <dt class="comment">コメント数</dt>
                                    <dd class="comment"><a href="#">3コメント</a></dd>
                </dl> -->
                <dl class="entryTags">
                    <dt class="tag">タグ</dt>

                        <?php if (count($this->tags) > 0): ?>
                            <?php foreach ($this->tags as $cnt => $tag): ?>
                            <dd class="tag"><a href="<?php echo $this->baseUrl('page/tag/id/') . $tag['id'] ?>"><?php echo $this->escape($tag['name']) ?></a></dd>
                            <?php endforeach ?>
                        <?php else: ?>
                            <dd class="tag">なし</dd>
                        <?php endif; ?>
                </dl>
            </div>

            <div class="entryBody">
                <p><?php echo $this->escape($entry['contents'] . "\n") ?></p>
            </div>

            <p class="moreRead"><a href="<?php echo $this->baseUrl('page/show/id/' . $entry['id']) ?>">続きを読む</a></p>

            <div class="socialButton">
                <ul>
                    <li class="twitter"><a href="https://twitter.com/share" class="twitter-share-button" data-lang="ja" data-hashtags="setucocms">ツイート</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></li>
                    <li class="hatena"><a href="http://b.hatena.ne.jp/entry/" class="hatena-bookmark-button" data-hatena-bookmark-layout="standard" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only.gif" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="http://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script></li>
                    <li class="plusone"><g:plusone size="medium"></g:plusone></li>
                    <li class="facebook"><div class="fb-like" data-send="false" data-layout="button_count" data-show-faces="false"></div></li>
                </ul>
            </div>

        </div></div></div></div></div></div> 
        <!-- entry END -->
    <?php endforeach; ?>

<?php else: //ページが公開されていない場合 ?>
  <p>ページが公開されていません。</p>
<?php endif; ?>