<?php
/**
 * 閲覧側のフッター
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Layout
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $siteInfos  サイト情報       
 * @author      suzuki-mar
 */
?>

 <footer>
     
     <!-- footer_inner START -->
     <div class="footer_inner">

         <?php if ($this->tagClouds !== false): //タグがなかったら表示しない?>
         <!-- tagCloud START --> 
         <div id="tagCloud"> 
             <h3><img src="/images/front/setucocms/h_tagCloud.png" alt="タグ" /></h3>
             <ul> 
                 <?php foreach ($this->tagClouds as $tag): ?>
                 <li class="level<?php echo $tag['level'] ?>">
                     <a href="<?php echo $this->baseUrl("/page/tag/id/{$tag['id']}") ?>"><?php  echo $this->escape($tag['name']) ?></a>
                 </li>
                 <?php endforeach;?>
             </ul> 
         </div> 
         <!-- tagCloud END -->
	       <?php endif;?>
         
         <p class="backTop"><a href="#wrapper">ページの先頭に戻る</a></p>
         
     </div>
     <!-- footer_inner END -->
     
     <!-- copyright_area START -->
     <div class="copyright_area">
         <p class='copyright'>Copyright &copy; <?php echo $this->siteInfos['start_year'] ?> <?php echo $this->escape($this->siteInfos['name']) ?> AllRight reserved.</p>
     </div>
     <!-- copyright_area END -->
         
 </footer>