<?php
/**
 * 閲覧側のヘッター
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Layout
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $siteInfos  サイト情報       
 * @author      suzuki-mar
 */
?>

<header> 
    <div id="header_inner"> 
        <h1><a href="<?php echo $this->baseUrl('') ?>" tabindex="1"><?php echo $this->escape($this->siteInfos['name']) ?></a></h1>
        <p class="descript"><?php echo $this->escape($this->siteInfos['comment']) ?></p> 
        <ul class="utility">
            <!-- <li><a href="#"><img src="/images/front/setucocms/icn_rss.png" alt="RSS" /></a></li> -->
            <li><a href="https://twitter.com/#!/SetucoCMS" target="_blank"><img src="/images/front/setucocms/icn_twitter.png" alt="ツイッター" /></a></li>
            <li><a href="http://www.facebook.com/SetucoCMS" target="_blank"><img src="/images/front/setucocms/icn_facebook.png" alt="フェイスブック" /></a></li>
        </ul>
    </div>
</header>
