<?php
/**
 * 閲覧側のレイアウトファイル
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Layout
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       String  $pageTitle  ページのタイトル $pageTitleはアクションごとに定義する
 * @param       array   $siteInfos  サイト情報
 * @author      suzuki-mar
 */


//ページタイトルがある場合とない場合でページタイトルの形式を変更する
if (empty($this->pageTitle)) {
    $this->headTitle($this->escape($this->siteInfos['name']));
} else {
    $this->headTitle($this->pageTitle)->setSeparator(' | ')->headTitle($this->escape($this->siteInfos['name']));
}

?>
<?php echo $this->doctype() . "\n" ?>
<html> 
    <head> 
        <meta http-equiv="content-type" content="text/html; charset=utf-8" /> 
        <meta http-equiv="Content-Language" content="ja" />
        <meta http-equiv="content-style-type" content="text/css" /> 
        <meta http-equiv="content-script-type" content="text/javascript" />

        <meta name="author" content="ErinaMikami with SetuCMS Project" />
        <meta name="copyright" content="<?php echo $this->escape($this->siteInfos['name']) ?>" />
        <meta name="generator" content="SetucoCMS <?php echo APPLICATION_VERSION ?>" />
        <meta http-equiv="imagetoolbar" content="no" />

        <meta name="description" content="<?php echo $this->escape($this->siteInfos['comment']) ?>" />
        <meta name="keywords" content="<?php echo $this->escape($this->siteInfos['keyword']) ?>" />

        <link rel="start" href="<?php echo $this->escape($this->siteInfos['url']) ?>" title="このサイトのトップページ" />

        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/css/style.css') ?>" media="screen" />
        <!--[if lt IE 9]>
        <script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?php echo $this->headTitle() . "\n" ?>

        <!-- plusone+ START -->
        <script type="text/javascript">
          window.___gcfg = {lang: 'ja'};

          (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
          })();
        </script>
        <!-- plusone+ END -->
    </head>
    <body>
      <!-- Facebook Javascript SDK START -->
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
      <!-- Facebook Javascript SDK END -->

        <!-- wrapper START -->
        <div id="wrapper">

            <!-- header START -->
            <?php echo $this->render('header.phtml'); ?>
            <!-- header END -->

            <!-- content START -->
            <div id="content">

                <!-- mainContent START -->
                <div id="mainContent">
                    <?php echo $this->layout()->content . "\n" ?>
                </div>
                <!-- mainContent END -->

                <!-- subContent START -->
                <div id="subContent">
                    <?php echo $this->render('navi.phtml') ?>
                </div>
                <!-- subContent END -->

            </div>
            <!-- content END -->

        </div>
        <!-- wrapper END -->

       <!-- footer START --> 
       <?php echo $this->render('footer.phtml') ?>
       <!-- footer END -->

    </body>
</html>
