<?php
/**
 * 閲覧側のナビゲーションメニュー
 * カテゴリー一覧と、タグクラウド
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Layout
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $categoryLists  カテゴリー一覧の配列       
 * @param       array   $tagClouds タグクラウドが入っている配列
 * @author      suzuki-mar
 */
?>

<!-- navArea START --> 
<div id="navArea">

    <!-- navArea START --> 
    <div id="navArea"> 

        <form action="<?php echo $this->baseUrl('/page/search/') ?>" method="get">
            <dl> 
                <dt><label for="keyword">フリーワード検索</label></dt> 
                <dd><input type="text" name="query" id="keyword" value="<?php echo mb_strlen($this->keyword, 'UTF-8') > 0 ? $this->keyword : '検索ワードを入力' ?>" onfocus="if (this.value == '検索ワードを入力') { this.value=''; }" onblur="if(this.value == '') { this.value='検索ワードを入力'; }" tabindex="2" /></dd> 
            </dl> 
            <p><input type="submit" value="検索" tabindex="3" /></p> 
        </form>

        <!-- navList START --> 
        <div class="navList"> 
            <h3><img src="/images/front/setucocms/h_nav_setucocms.png" alt="SetucoCMSとは何か" /></h3> 
            <p>日本電子専門学校電設部有志によるCMS開発プロジェクトです。SetucoCMSのコンセプトは”自由”。サイトを制作する人に自由さと楽しさを感じてもらいたい。そんな想いを込めたほんわか系CMSです。</p>
            <p class="linkText"><a href="#">SetucoCMSプロジェクト</a></p>
        </div> 
        <!-- navList END --> 

        <!-- navList START --> 
        <div class="navList"> 
            <h3><img src="/images/front/setucocms/h_nav_popular.png" alt="人気のエントリー" /></h3> 
            <ul>
                <li><a href="#">1stリリースを迎えて-謝辞-</a></li>
                <li><a href="#">1stリリースを迎えて-謝辞-</a></li>
                <li><a href="#">1stリリースを迎えて-謝辞-</a></li>
                <li><a href="#">1stリリースを迎えて-謝辞-</a></li>
                <li><a href="#">1stリリースを迎えて-謝辞-</a></li>
            </ul>
        </div> 
        <!-- navList END --> 

        <!-- navList START --> 
        <div class="navList"> 
            <h3><img src="/images/front/setucocms/h_nav_category.png" alt="カテゴリー" /></h3> 
            <ul>
                <?php foreach ($this->categoryLists as $category): ?>
                <li>
                    <?php if ($category['is_used']): //カテゴリーを使用しているページがあるか?>
                    <a href='<?php echo $this->baseUrl("/page/category/id/{$category['id']}") ?>'><?php echo $this->escape($category['name']) ?></a>
                    <?php else: //使用していない場合はリンクしない?>
                    <span><?php echo $this->escape($category['name']) ?></span>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            </ul>
        </div> 
        <!-- navList END --> 

        <!-- navList START --> 
        <div class="navList"> 
            <h3><img src="/images/front/setucocms/h_nav_archive.png" alt="アーカイブ" /></h3> 
            <ul>
                <li><a href="#">2011年6月（5）</a></li>
                <li><a href="#">2011年6月（5）</a></li>
                <li><a href="#">2011年6月（5）</a></li>
                <li><a href="#">2011年6月（5）</a></li>
                <li><a href="#">2011年6月（5）</a></li>
                <li><a href="#">2011年6月（5）</a></li>
                <li><a href="#">2011年6月（5）</a></li>
                <li><a href="#">2011年6月（5）</a></li>
                <li><a href="#">2011年6月（5）</a></li>
                <li><a href="#">2011年6月（5）</a></li>
            </ul>
            <p class="linkText"><a href="#">さらに過去を表示する</a></p>
        </div> 
        <!-- navList END --> 

        <!-- navList START --> 
        <div class="navList"> 
            <h3><img src="/images/front/setucocms/h_nav_writer.png" alt="ライター" /></h3> 
            <ul class="writerList">
                <li><a href="#"><img src="/images/front/setucocms/writer/icn_writer_noimage.png" alt="" /><br /><span>aki</span></a></li>
                <li><a href="#"><img src="/images/front/setucocms/writer/icn_writer_fossilcat.png" alt="" /><br /><span>fossilcat</span></a></li>
                <li><a href="#"><img src="/images/front/setucocms/writer/icn_writer_re_3_19.gif" alt="" /><br /><span>re_3_10</span></a></li>
                <li><a href="#"><img src="/images/front/setucocms/writer/icn_writer_noimage.png" alt="" /><br /><span>skyguild</span></a></li>
                <li><a href="#"><img src="/images/front/setucocms/writer/icn_writer_noimage.png" alt="" /><br /><span>akitsukada</span></a></li>
                <li><a href="#"><img src="/images/front/setucocms/writer/icn_writer_noimage.png" alt="" /><br /><span>karino777</span></a></li>
                <li><a href="#"><img src="/images/front/setucocms/writer/icn_writer_noimage.png" alt="" /><br /><span>mar</span></a></li>
                <li><a href="#"><img src="/images/front/setucocms/writer/icn_writer_noimage.png" alt="" /><br /><span>tar-san</span></a></li>
            </ul>
        </div> 
        <!-- navList END --> 

        <!-- navList START --> 
        <div class="navList"> 
            <h3><img src="/images/front/setucocms/h_nav_link.png" alt="リンク" /></h3> 
            <ul>
                <li><a href="#">SetucoCMSプロジェクト</a></li>
                <li><a href="#">日本電子専門学校</a></li>
                <li><a href="#">日本電子専門学校電設部</a></li>
            </ul>
        </div> 
        <!-- navList END --> 

     </div> 
    <!-- navArea END -->
     
 </div>
<!-- navArea END -->

